### ISSUE TITLE
Can't receive messages -FB

### ISSUE THREAD

**Issue by kathdrib** [filmor/webos-messaging#15]
I can send chat with the chat account (Facebook), they took a little time to be send. But I don't receive the response, It actually appears in the fb chat in my PC or in the messages, but not here.

I have installed the ipk with "palm-install", not the preware. Could that be the problem?

Thanks!

**Comment by filmor** [comment]
I don't think installing with `palm-install` is a problem, I think it uses the same mechanism for installation (though it might pose a permission problem). However if you are able to connect and send the installation worked. Could you upload the `purple_transport.log` file? Before you do so _please_ check if it contains any sensitive information!

**Comment by filmor** [comment]
I'll close this due to inactivity, feel free to reopen.
