### ISSUE TITLE
Unable to build (link errors with gcrypt and some other bits)

### ISSUE THREAD

**Issue by larkery** [filmor/webos-messaging#16]
Hello, I'm trying to build a patched version of your marvellous messaging module which fixes a few minor issues in the javascript side of things that cause me problems. I can patch the JS on the device and make it behave as I would like, but that's obviously not ideal so I would rather rebuild, test and send you a pull request.

Anyway, I am using the PDK cross-compiler, and have done waf get_libs, waf configure, and in waf everything compiles and then dies at the final linking, saying:

```
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libgthread-2.0.so.0, needed by ../build_lib/lib/liblunaservice.so, not found (try using -rpath or -rpath-link)
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libmjson.so, needed by ../build_lib/lib/liblunaservice.so, not found (try using -rpath or -rpath-link)
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libgoodfork.so.0, needed by ../build_lib/lib/liblunaservice.so, not found (try using -rpath or -rpath-link)
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libPmLogLib.so, needed by ../build_lib/lib/libmojocore.so, not found (try using -rpath or -rpath-link)
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libgcrypt.so.11, needed by ../build_lib/lib/libgnutls.so, not found (try using -rpath or -rpath-link)
/opt/PalmPDK/arm-gcc/bin/../lib/gcc/arm-none-linux-gnueabi/4.3.3/../../../../arm-none-linux-gnueabi/bin/ld: warning: libgpg-error.so.0, needed by ../build_lib/lib/libgnutls.so, not found (try using -rpath or -rpath-link)
```

And then giving a big list of missing symbols from these places; most of the missing symbols are required by gnutls and are from libgcrypt which I can't find anywhere, but a few are from other things, like 

```
../build_lib/lib/liblunaservice.so: undefined reference to `g_thread_init'
```

which it should be resolving from libgthread in ../build_lib/lib/.

The command which dies is:

```
['arm-none-linux-gnueabi-g++', 'src/BuddyListConsolidator.cpp.31.o', 'src/BuddyStatusHandler.cpp.31.o', 'src/ConnectionStateHandler.cpp.31.o', 'src/DisplayController.cpp.31.o', 'src/IMLoginState.cpp.31.o', 'src/IMMessage.cpp.31.o', 'src/IMServiceApp.cpp.31.o', 'src/IMServiceHandler.cpp.31.o', 'src/IncomingIMHandler.cpp.31.o', 'src/LibpurpleAdapter.cpp.31.o', 'src/OnEnabledHandler.cpp.31.o', 'src/OutgoingIMCommandHandler.cpp.31.o', 'src/OutgoingIMHandler.cpp.31.o', 'src/SendOneCommandHandler.cpp.31.o', 'src/SendOneMessageHandler.cpp.31.o', 'src/Protocol.cpp.29.o', 'src/Util.cpp.29.o', '-o', '/home/hinton/src/webos/webos-messaging/build/org.webosinternals.purple.transport', '-march=armv7-a', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L../build_lib/lib', '-L.', '-L../build_lib/lib', '-lpurple', '-lglib-2.0', '-lgobject-2.0', '-lgmodule-2.0', '-llunaservice', '-lmojoluna', '-lmojocore', '-lcjson', '-lmojodb', '-lxml2', '-lgnutls', '-lresolv', '-Wl,-rpath=/var/usr/lib']
```

which looks OK to me (the -L in particular), so I guess my question is:

Is there some build environment detail I am missing here?

**Comment by larkery** [comment]
Ten minutes of hacking later, I am able to build the widget by hand with the following gruesome steps:
1. yank libgcrypt, libgpg-error and libPmLogLib out of /usr/lib on my palm device
2. add the so files to the list of objects in the build command

But this is clearly a wrong thing to do

**Comment by larkery** [comment]
So for any interested readers, the path to solving this was to get the libraries mentioned and add them to the library list because ld does not resolve transitive dependencies, it just complains about them.

**Comment by filmor** [comment]
Hmm, there seems to be a problem with the `get_libs` part here. Adding the `so`-files should not be an option. Do you have global `CFLAGS` set that might interfere?

**Comment by larkery** [comment]
I don't have any CFLAGS set. Do you have a libgcrypt or libPmLogLib available in your build environment? Perhaps my PDK is wrong somehow?I find adding them to the library list in the build_lib's python parts works, which is presumably not statically linking them. I don't know much about the linker but I guess it needs to see the so files containing any used symbols to know how to jump to them, so it seems like libgcrypt and so on ought to be available to it somewhere.Anyhow, now I can build it I need to work out why it doesn't like my xmpp server!On 2 Jan 2014 11:13, Benedikt Sauer notifications@github.com wrote: Hmm, there seems to be a problem with the get_libs part here. Adding the so-files should not be an option. Do you have global CFLAGS set that might interfere?

**Comment by filmor** [comment]
Okay, I'll add the respective files to the `libs` tarball. I wonder why this worked before, I'll have a closer look on the weekend …
